name: Installer ISO build
on:
  push:
    branches:
    - 'master'
jobs:
  build:
    name: Installer ISO build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Change directory
        run: cd $GITHUB_WORKSPACE
      - name: Build ISO
        id: build_iso
        run: ./build-iso-docker.sh
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.build_iso.outputs.version }}_${{ steps.build_iso.outputs.id }}
          release_name: ${{ steps.build_iso.outputs.version }} (${{ steps.build_iso.outputs.id }})
          draft: false
          prerelease: true
      - name: Upload ISO
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/${{ steps.build_iso.outputs.iso_file_name }}
          asset_name: ${{ steps.build_iso.outputs.iso_file_name }}
          asset_content_type: application/x-cd-image
      - name: Upload sha256sum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/sha256sum.txt
          asset_name: sha256sum.txt
          asset_content_type: text/plain
